#The dimension from where you can teleport to the mining dimension and back
overworld_dimension = "minecraft:overworld"

[world_generation]
	#Range: 0.0 ~ 1.0
	cave_percentage = 0.3
	#Range: 0.0 ~ 1.0
	canyon_percentage = 0.02
	lava_lakes = true
	spawners = true
	stone_variants = true
	ores = true
	#If lava should be generated in caves below level 11
	lava = true

